# add docker compose basic config
version: '3.7'
services:
  next:
    container_name: next-docker
    image: next-docker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEXTAUTH_SECRET=test
    ports:
      - "3000:3000"
