import { Stack } from '@mui/material';
import type { Metadata } from "next";
import { getServerSession } from 'next-auth';
import { Inter } from "next/font/google";
import { BaseThemeComponent } from './BaseThemeComponent';
import Header from './_Header/Header';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await getServerSession();

    return (
        <html lang="en">
            <body className={inter.className}>
                <BaseThemeComponent>
                    <Stack height={'100%'}>
                        {!!session &&
                            <Header />
                        }
                        {children}
                    </Stack>
                </BaseThemeComponent>
            </body>
        </html>
    );
}
