import { Stack } from '@mui/material';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { LinkButton } from '../shared/components/LinkButton';
import { BaseThemeComponent } from './BaseThemeComponent';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <BaseThemeComponent>
                    <Stack spacing={2} direction={'row'}>
                        <LinkButton href="/">Customer</LinkButton>
                        <LinkButton href="/service">Service</LinkButton>
                        <LinkButton href="/manager">Manager</LinkButton>
                    </Stack>
                    {children}
                </BaseThemeComponent>
            </body>
        </html>
    );
}
